spring.datasource.url=jdbc:postgresql://localhost:5002/Logistics_Operation
spring.datasource.username=admin_user
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

logging.file.name=spring-startup.log
spring.web.resources.chain.cache=false
spring.web.resources.cache.period=0