# Application Name
spring.application.name=Axle Logistics

#PostgreSQL DB Config
spring.datasource.url=jdbc:postgresql://localhost:5002/Logistics_Operation
spring.datasource.username=admin_user
spring.datasource.password=root

#Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
